-- MySQL Script generated by MySQL Workbench
-- 11/10/21 22:24:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(10) NULL,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(60) NULL,
  `apellidoPa` VARCHAR(60) NULL,
  `apellidoMa` VARCHAR(60) NULL,
  `telefono` VARCHAR(12) NULL,
  `correo` VARCHAR(45) NULL,
  `sexo` VARCHAR(12) NULL,
  `direccion` VARCHAR(60) NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_empleado_persona_idx` (`idPersona` ASC),
  CONSTRAINT `fk_empleado_persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_empleado1_idx` (`idEmpleado` ASC),
  CONSTRAINT `fk_usuario_empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidadMedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidadMedida` (
  `idUnidadMedida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idUnidadMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`familia` (
  `idFamilia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idFamilia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idProducto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `precio` DECIMAL(7,4) NULL,
  `stock` DECIMAL(7,4) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `codigoBarra` VARCHAR(45) NULL,
  `idUnidadMedida` INT NOT NULL,
  `idFamilia` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_producto_unidadMedida1_idx` (`idUnidadMedida` ASC),
  INDEX `fk_producto_familia1_idx` (`idFamilia` ASC),
  CONSTRAINT `fk_producto_unidadMedida1`
    FOREIGN KEY (`idUnidadMedida`)
    REFERENCES `mydb`.`unidadMedida` (`idUnidadMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_familia1`
    FOREIGN KEY (`idFamilia`)
    REFERENCES `mydb`.`familia` (`idFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quiebre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quiebre` (
  `idQuiebre` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DECIMAL(7,2) NULL,
  `fecha` DATE NULL,
  `idProducto` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idQuiebre`),
  INDEX `fk_quiebre_producto1_idx` (`idProducto` ASC),
  INDEX `fk_quiebre_usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_quiebre_producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiebre_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
